/*
    Copyright 2021, 2022, 2023 David Healey

    This file is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This file is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with This file. If not, see <http://www.gnu.org/licenses/>.
*/

namespace Paths
{
    reg pathData;
    const icons = {};    
      
    // X - Reza
    pathData = "277.t0lP.73PWjOVCwFhFC4PLxVUCI1UND4PvzMUCckCQNTuzO0PHZLjCEVYSMjXZ6GjCUf0RMTnJ.4PEXsTCIuvONTXkM0PrwJ+MND6wa0PrYlMLNTXkM0Phco6KNTAVK0Pdo2hCUf0RMDzxr3PgU1TCIV.qq3P+S+TCEv5JNTbcS0PPKyhCwHaUMDaVjOiCcQ9XMDaPKyhCIZgbMjXArthC4OEcMT.qq3Pw0eWCAsLKNTyL50Ph4mdKNTJb70P259hCkBGeMjY1v3PMynWCwFq723PBAvVCwl7B+3PMynWCIVvJ.4PovwWCouePNTJb70PHZLjC0LidMjXW4PjC8R+cMzUND4P8RQWCgnwPNjnEx0PiUF...";
  
    icons.x = Content.createPath();
    icons.x.loadFromData(pathData);
    
    // Check - Reza
    pathData = "200.t0ltY44Pb8xnDIlv024PdYwnDU4TcNjWVLJQ99NmCw0KiRDatIzkCgpljRDaOJLkCAq9iRjX35EkCIa3iRzh7N4PxF9nDMIVSNDr5OJQhsI8RNjqSPJQaRujCkCOjRzjXM4P2TEoDw1JGZ4PUCRoDI1NuZ4PYqRoDkX3VNDqvTJQAVwkCgpLkRjXGZ1kCgpMkRjr8d4PUCSoDsH+WNzKgTJQroaVdNz1INJQhIaudNT2vMJQx1qmCIFRiRjtY44Pb8xnDMVY...";
  
    icons.check = Content.createPath();
    icons.check.loadFromData(pathData);    
    
    // Add - Reza
    pathData = "286.t0VIFPaPkX.pBwVFDnXPkX.pBwVFDnXPhVXmBIVFDnXPx18lBc8nDFjnEpoPxf.eAIZgZJjXbRraAIZgZJjLHPVPx18lBICBjEjnE1oPrICBjETIFfpPrICBPDTIFfpPhwIwBDTIFfpPjAA7.UiWoJDYP.OPkXvpBIFYP.OPU3JqBUKxBDTIF3pPxf.DAUhAtJDaxf.YAUhAtJDaxf.YAgpg3JjXxf.YAgoK5JTsH6VPnZ3tBICB7EDpFtqPhc8nDFDpFtqPYPfhAgoK5JTFDnXPnZHtBwVFDnXPkXfqBwVIFPaPkXfqBI13kpaPkXfqBUhA.GTEtxpPkX.vAUhAqJjXkX.vAUiWoJD7mpaPkX.pBUhAzFTIFfpPiUF...";
        
    icons.add = Content.createPath();
    icons.add.loadFromData(pathData);
    
    // Edit - Reza
    pathData = "190.t0F.UAnP.rmlBIVeo5mP.rmlB45o7IjocqoP..xdBAfnaJDa.zcgBAP9iJjXqP1gBk7ahJzJjcnPwH+mBAP2EJD.p4oPrAPFCJD.htoPhkRUBJjocqoPBUUfBAvdZJD.UAnP.rmlBMVa.H2cBA.ecJDa.HjUBAfJtJDa.nsYBAPf1JDa.T.gBAvzkJDa.H2cBA.ecJzXsA.VRID.l+pPrA..LID.KtqPrAfJiID.agqPrA.VRID.l+pPiUF...";
    
    icons.edit = Content.createPath();
    icons.edit.loadFromData(pathData);
    
    // Trash - Reza (17x19)
    pathData = "652.t0F.M+rP.PmkBwF.aGrP.DnmBwF.hOrP.LfnBwF.2XrP.LfnBwF.eRrP.3ymBwF.P7rP.bSlBwF.iPsP.LfnBwF.4YsP.LfnBwF.M+rP.PmkBMVa.TluBAfAkJjXFXVuBAfAkJD.XxqPBLaoBA.l7JD.HZpPhA.l7Jj+bcpPFXVuBAPBnJD.k4qP.j.pBwF.8+qP.j.pBIF.8+qPCl.pBAP++JTeJfpP.z+uBAvBnJDa.LaxBAvBnJDa.HaxBAPBnJDa.DXyBAPBnJDa.3WyBAvBnJDa.Dw1BAvBnJDa.Dw1BAPBnJDa.jJ2BAPBnJjX8gZ2BAPBnJD.24sP9y0oBAvcdKD.HZpPhAvcdKj.yVpP8gZ2BAfAkJD.oxsP.XPoBwF.k4qP.XPoBMVa.vGvBAvBqJDa.z0vBAfM5JjX.z0vB0rv6JT21QrP.XPuBAfzEKD.FzqPrAPOUKD.FzqPhMBlVKD.FzqP.D60B0rv6JD.wdsP.XitBwF.SpsP.rvpBwF.DQsP.rvpBIVhEQsPkuwpBAPSTKzFqrpP.zD0BA.OqJDa.zD0BAvg1JjX.zD0B4oc2JTHLNsP.jCtBA.mRKD.4fqPhYNqQKD.4fqP.nNzB4oc2JD.pCsP.bnsBwF.pCsP.vypBIF.pCsParxpBMe7PKjXarpP.POzBAvBqJDa.ngxBAvBqJjXLvgxBI1FqJD.jnrParxpBA.IJKD.7rpPrA.IJKD.GZqPhA.IJKjm1cqPaHVxBAPN3JD.ygrP.jCtBI12BdrP.jCtBAPvFKjm1cqP.DrwBAvg1JDa.DrwBA.OqJjX.DrwBswJqJTbHarPhswpBAvxFKD.KrpPrA.e.KD.KrpPiUF...";
    
    icons.trash = Content.createPath();
    icons.trash.loadFromData(pathData);
    
    // Star - Reza
    pathData = "389.t0lShR6PQK1qBI1CcM6PjsuqBkAcwNTuz4pPYPWrC0KctJjXYPWrC0KctJjiWC6PYPDpB0hXvNjPfNpPhQ1FvNzaREpPLc5qCMvZgJTci85PjB6nBIlUt65PuIEpBQ0TtNTuz4pPTMkqC0KctJjXTMkqC0KctJjmuw5PirwqBAVIqNjkC9pPh02upNDMy+pPqbnpCUMdwJzOUq5P3jnrBIFxVu5PpaZsBc9VsNzoaoqPmuUqCc5V5JjXmuUqCc5V5JjsSy5P98ivBYmerNjGZcrPhoGUrNTirlrPIwLqCoqGJKT.az5Pc8TxBIlfv35PdnkwBY83uNjx1FrPVO9qCorsAKjXVO9qCorsAKz9oE6P87cwBkuexNjcSirPhAB3xNTsHnrPxL1rCE.vIKDE9L6PGYuwBIVTnK6P1McvBU5ZxNzoaoqPktlrCc5V5JjXktlrCc5V5JD4fO6PKbcsBwh3zNzW5JqPhkFO0NTWOFqPQgSsCckiuJTShR6PRK1qBMVY...";

    icons.star = Content.createPath();
    icons.star.loadFromData(pathData);

	// Star Outline - Reza
	pathData = "195.t0F.pkoP..BKBwF.TioP.3kKBwF.3ZoP.XmMBwF.PEoP.XJNBwF.RToP.HRPBwF.hQoP.PLSBwF.pkoP.f7QBwF.x4oP.PLSBwF.B2oP.HRPBwF.DFpP.XJNBwF.bvoP.XmMBMVa.nVlBAf0wHDa.rylBA.y3HDa.DvmBA.U5HDa.7EmBA.Q.IDa.fMmBAfNHIDa.nVlBA.0DIDa.vekBAfNHIDa.TmkBA.Q.IDa.P8jBA.U5HDa.j4kBA.y3HzXkA..";
    
    icons.starOutline = Content.createPath();
    icons.starOutline.loadFromData(pathData);
        
    // Settings - Reza
    pathData = "868.t01M4e7PCBv.Cw17cc7PCBv.CI13Ec7PcSj.CYRHGOjsSFvPGEuwCQJ7.LDaAA1wCAqD.LjXGZ7wCkDi9KTTHe7Psy+9BsIYGOTjsouPhQL.GOTMdiuPLykwCMd43Kzo1W7P46m9Bw1jHV7PKcC+BIFx1T7P+T29BMe2DOTPfquPc9GwCYme5KDac9GwCsdD3KjXc9GwCw0y0KjKMP7Pdo+7B8+eCOjW5OuPhAs7BOjW5OuPAAnvCw0y0KTP.J7PqGA9BwVP.J7P46m9BIFChH7PAAt9BcSxAOzO0suPtdWvC47M7KDa4kPvCkue5KjXyLJvCId43KDW++6Pz3M9BU3l+NTjsouPh45M+NT67uuPYlyuCwLi9Kz2e96PvJA.Cw1NO.7PnEO.CIFWe+6P4PY.CArt+NjGEIvPvJ5uCMH.CLDabRvuCMH.CLjX3OmuCMH.CLTt926PhV9.Ckq+8Nju+SvPhkq+8NjWZXvP3OmuCsy+FLDmD76P67uACwFrh96P67uACIFv596Pep6ACw02+NjwqgvP67.vCcoCILDaIF5uCse5ILjXCsyuCYnsJLDV476Pz3+BC8Rm+Nj3EyvPhUN..ODjM1vPcSJvCkahMLj.KD7PtzKCCwF72E7PSM9BCIVdIG7PYQDCC4jHBOD1NxvPiAnvC06uLLDaiAnvC0l7MLjXiAnvCU6DOLj7xK7Pz3+CCEBfCODM9+vPhAUCDODM9+vP+9GwCU6DOLzu+Q7PsIeCCw1u+Q7P.ALCCIF8cS7Pb9HCCkrMEOTGEwvPygXwCcA4KLDaeTewC8VuLLjXEtkwCoehMLDO+a7PQ2XCCMwXGOzHFyvPhotwGOTc9uvP+S7wCUnsJLTtdc7P7ndBCwFRwa7Pa8PBCI1Igb7PJxFBCQdQGOzX6dvPz20wCw2+FLDaXk+wCw2+FLjXcnHxCw2+FLzN+i7PcogACsy+HOz++SvPhow+HOzWkOvP7mHxCIH.CLzM4e7PBBv.CMVac92vCEW+ILjXQ1gvCEW+ILzk9C7PFD7ACco+.Oj99SvPhco+.Oj67HvPQ1gvCUL..LTm+M7PEC..CIVpgS7PEC..CMJ.FOj67HvPiBfwCou+DLjXiBfwCYPvGLTpgS7Pw0eBC04eCOTb8mvPiUF...";
    
    icons.settings = Content.createPath();
    icons.settings.loadFromData(pathData);
    
    // Eject - Reza
    pathData = "362.t01wKSgPP0.CBwlPfYaPP0.CBI1ep4ZPP0.CB878mFDV45fPOe+oAUhARHjXOe+oAIuTUHzhr4ZP...FBIDX1FD..fgPrc7xTHD..fgPhIZwXHD..fgP...GBIuTUHD..vgPkXfDBIF..vgPXkqCBIZwXHDTMvfPGuLEBAUCLHzXsswK7FTdoeePrQKxQHTdoeePhAVYWHTdoeePvJ+FBU1NxGDrxugPLcy5AwFrxugPoEY5AIFrxugPCWu4AUNTaHDKGRdPjsiFBMwfhGjXkCcFBYiWgGDY6jgPT2D3AEtdXHjJb8cPrYRL7GTmDyZPh4mZ0Gz.qXZPW5l5AMvJlFz6mNdPcRLqAwVmu2ZPDW+2AIVpwuZPAUS3AMzhpFjHvJdPQgapA42OjGjXpbHpAAS2kGjHaeZPIv54AIx1mFTWOldPrIx1mFDP0rdPhMx1mFDY6HePCWOrAkW52GzFuvaP4k98AMVY...";
    
    icons.eject = Content.createPath();
    icons.eject.loadFromData(pathData);

	// Caret up - Reza
	pathData = "293.t0FxW.lPFdkXBw1+0zkPFdkXBwFAMfkPYk8VBIVeYekP9f4VBYijWIDbyskPCjzUBA2baIjXLAvUBA2baITA4ZkP8f4VB0WgVITVYukPrMHWQIjgWIlProqdNIjgWIlPhUnBNIjgWIlPdWZSBoo.hIj.60jPgAXXBIVIP0jPo3OXB86YMITlnAlP0baSBwPAfIDa5WnUBk46TIjXAlqUB4mqTIDx.bkPvlHUBAXRWIDrIRkPhUqjWIDrIRkP5m8UB0mqTITfMfkPY9NUBwVQbClPLT.XBIlOQDlPSdDXBIKKgIjufBlPxxRXBws9fIjXxxRXB45IgID7kDlP4SUXBI3EgIjX.FlPhUJ6fIjlBHlPCdHXBc3UhIjxW.lPGdkXBMVY...";
	
	icons.caretUp = Content.createPath();
	icons.caretUp.loadFromData(pathData);
    
    // Caret down - Reza
    pathData = "293.t0FxW.lPvlHUBw1+0zkPvlHUBwFAMfkPcevVBIVeYekP3izVBYijWIjwsskPCjzUBYbaaIjXLAvUBYbaaITA4ZkP4izVB0WgVIT2GrkPrMHWQIDrIRkProqdNIDrIRkPhUnBNIDrIRkPdWZSBwo2TIj.60jPUCVUBIVIP0jPMLdUB86YMITm3YkP0baSBoB2VIDa5WnUB0Y7gIjXAlqUBgqLhIDx.bkPFdkXBAXRWIjgWIlPhUqjWIjgWIlP5m8UBkqLhITfMfkPcFeXBwVQbClPpvsUBIlOQDlPiloUBIKKgIDd.YkPxxRXBok4UIjXxxRXBgXtUID7kDlP8vXUBI3EgID0fUkPhUJ6fIDmdSkPCdHXB8ZhTIjxW.lPulHUBMVY...";

    icons.caretDown = Content.createPath();
    icons.caretDown.loadFromData(pathData);

	// Caret left - Reza
	pathData = "293.t0FbNlcPPhEzAwFbNlcP9SoxAwVERxbPHLDvAI12OvbP5u8uAQjwKGTaM8aPDY7xAYvt9FjXDY7xAgYJ9Fz2OvbPJrYuAUgjLGz9yzaPrAmiYGjAhKaPrAmiYGDcdzZPhAmiYGTB9vZPYRN1AsKcqFzIfecPC7wpAI1saacPHkrpAYIrUGTe3qZP7kN0Ao1kqFDaV5quAQOM8FjXfwiuAI.m8FTwx2aPOphuAUr78Fz+65aPhUr78FDZN8aPfwiuAIO2+Fjk95aPAPDvAwFeoScPJFdzAI1htUcP6sjzAANHVGDYBJcPaTs0AQlfRGjX+5x0AQlfRGDUIdcPfSmzAYB3WGDAXIcPhYI4XGTRBHcPu4X1Ac.NQGzaNlcPShEzAMVY...";
	
	icons.caretLeft = Content.createPath();
	icons.caretLeft.loadFromData(pathData);

	// Caret right - Reza
	pathData = "293.t0Vwx2aPJu0cAwVwx2aPmR8ZAwFHuqbP5ByUAIlUwsbPdJlUAEutKGDgEUUPwq6xAYKHTEjXwq6xAsc+REjUwsbP8BdTAAx6JGDnRDUPrUr78FjstwSPrUr78FjjmCSPhUr78FDul7RPbxouAABksDjCg9aPvhNKAIlekBbP6zCKA8IzAGDoaxRP4dovA4W1sDDaeJL1AIIEQEjXUST1A4p3QEDbNlcPH+uTAAmiYGDphPUPhAmiYGzdGUUPUST1A8HYVEzmBicPrJyUAwVtWJbP91ldAIlpRHbPgFzdAUEXAGTbutWPZvJvAE2q6EjX1IEvAE2q6ET32+aPnQ4dA8Pn+FjrZsWPh8Im9FTOupWPFKeuAcqF4Ejwx2aPPu0cAMVY...";

	icons.caretRight = Content.createPath();
	icons.caretRight.loadFromData(pathData);

	// Triangle up - Reza
	pathData = "216.t0FW+QSPyVeFBIlUmTSPICWFBksxzDzFXigP4M4LAwmbXHDa18PDAYbHMHjXGVDDAE02LHDNt7PPAmKCB4SDNDTv4xfPhkD8LDTv4xfP1y8BAY02LHzASrPPFGRCBwVBdDMP7IGFBIV298LPfYKFBQ9nNCj6PjgPjOpy.UVaYHjXjOpy.sxlYHzHY6LPVibFBEeROCTM0mgPhUdlPCDo4ogP555z.4LzZHzYZbMPNCsFBwlUSBSPNCsFBIl7LISPNCsFBQT1yDTk5ogPX8GMAMa8YHzXkA..";

	icons.triangleUp = Content.createPath();
	icons.triangleUp.loadFromData(pathData);

	// Triangle down - Reza
	pathData = "216.t01JDwXPYhlFBwVKF1YPiewCBIF6f3YPNIqCBwATdFDGZ3fPevemAQKkMHjXSjZmAUDDMHT6hyYPajKCBAwAbFzF4xfPrI.ByEzF4xfPhwhTwEzF4xfP9d7aA8CDMHzwe7VPzRYCBIFKm6VPKDbCBALytEjNu2fP.yraAQHGNHjX.yraAwOdNHjL57VP+OsCBIcBvEDZW7fProtQIFzHnogPhE9pIFDlppgPJdihAUBzZHjAFqXPk.sFBIFjSsXPk.sFBgy2KFDjppgPvPDiAkIZZHzXkA..";

	icons.triangleDown = Content.createPath();
	icons.triangleDown.loadFromData(pathData);

    // Triangle left - Reza
    pathData = "216.t0Vh5RxPvLcTBIlSYRxPwjZTBMxbjLTT.GkP6lEICkhCRIDaMVXHCoxqZIjXvSWHCYZ3ZIDiqExP5cxVBw3ZgLDttskPhw3ZgLT80tkPwSWHCo79aITiEFxPF4BWBw1tYQxPG8LYBIFspQxPrLPYBcUfjLDidTlP0gIICwnGkIjXlOJICwnGkITTuRxPjeQYBkltjLjxITlPhU31jLzxeSlPOEOICESejIzSwSxP69.YBw1SwSxPy3rTBI1SwSxPL+kTBE71jLzs7GkPHpKICMyzQIzXkA..";

    icons.triangleLeft = Content.createPath();
    icons.triangleLeft.loadFromData(pathData);
    
    // Triangle right - Reza
    pathData = "216.t01AO0xPx5pVBwV15oxPw1fTBIFcgoxPQAbTBc1NpLjtnFkPMngJCgqzQIjXwieJC4C+QIzIimxPQ8kTBcx3oLDPMKkPrcx3oLDxNPlPhcx3oLjO7QlPvieJCks2jITCZnxPWiPYBI1HknxP9aQYB4JLpLTlcTlPAviJCkYGkIjXeLkJCkYGkID3ooxP8HPYBoqdpLDUNSlPrktSsLDUsvkPhY3WsLD15ukPoiVKCQPsaIT5n0xPF21VBIV5n0xPAbxVBQ3WsLTKgqkPF7TKCEqqZIzXkA..";

    icons.triangleRight = Content.createPath();
    icons.triangleRight.loadFromData(pathData);
    
    // Power - Reza
    pathData = "379.t01SmuTPJnmRBIl2iwRPJnmRB0+0RDjz6BkP8esDAA7bXIjX8esDA45JfIjskwRP10lYB8z4KEjcsYlPhUqZqEjcsYlPGwmfA45JfIzQ7IXP.OGVBI1Q7IXPRuKTB0JaqEjB5ojPPc9RAofdJIzXssHoEETle5jPrsg6PETle5jPrsg6PEz3HVkPrsHoEEz3HVkPi01SmuTPadFXBIF31mSPadFXBwxaqDjlWykPr71JAA7bXIjXr71JA4xEUIjm4OSPtqiTBg8++DDvPDkPrg8++DjCEPkPhI1G5Dzf3SkPDliMAUJlVIDg4XSP.OGVBIFg4XSPkI1VBUn6+DzAC2kPOc9RAcvvcIjXZ.9UAcvvcIjFUFVPjI1VBoQkgEDvygkPhoQkgETf4YkPCyQWAMQwTIT1RZUPPr8TBwV1RZUPnjOTBIFy9LVPM7fTB4UXrEjU6SkPdEFaAgCcXIjXdEFaAIA1bIjmW2UPZdFXB4z4KEjlmAlPiUF...";

    icons.power = Content.createPath();
    icons.power.loadFromData(pathData);
    
    // Question - Reza
    pathData = "974.t0VJTWzPm.3FBIFCRVzPm.3FBUBVEMTk7tgPXZRQCkIMbHjXKTOQCwIqbHjUOSzPkQTGBwWsDMjI62gPhI5lDMDSx5gP45HQCwlYeHTtNRzP8gAHBIVtNRzPh6FHBEukDMDX+BhPxbJQCITBgHjX5cKQCY0TgHzfKSzPhgWHBIz3DMjX3EhPhk2BEMjX3EhPGaRQC4lCgHTI0TzPaoCHBIlaDUzPa+1GBEwUEMTJV6gPazVQCseadHjXkLXQC0bAdHzhkVzPfGcGBkB0EMD3Q2gPhA+9EMD3Q2gPxwgQCIVAdHTp0XzPjwlGBIF3NYzPXNsGB00VFMDNR8gPcskQCUE5eHjXcskQCkUMfHTXWYzPwwGHB8vSFMjG9BhPhgsQFMDy+ChPCxiQC04NgHDfvXzP5CWHBIFYjXzPHZZHBENDFMzH1GhPCWeQCowWhHjXUacQC0w0hHTS9VzPg6yHBMAqEMDPVNhPhkclEMDasOhPmrXQComTjHDJ.VzP9WLIBI1G0UzPPkSIBA7aEMD0AWhP.+VQCE4WlHjX.+VQCIW2lHTO2UzPBvyIB4igEMzt6chPh4SkEMDc6dhPDeZQCI31mHjy8VzPBt8IBIFNnWzPBt8IBYW.FMTI5chP4kfQCEtslHjXo3fQCQvVlHDlQXzPIogIB09DFMDu0WhPhoiEFMDLQWhPDlgQCEOqkHzscXzPxfXIBI18gXzPxMVIBIHJFMj+5ThPpDiQCQvCkHjXQmiQCkv3jHjYEYzPi.KIBI8TFMjE1QhPho9gFMDemNhPJvpQCgGEiHzJ.azPK0qHBIFQTazPdXlHB4Z4FMDJ9GhPKQuQCQhggHjXoKvQCEhCgHzGJbzP7JHHB8gBGMzBi+gPhshBGMjHY7gPp0uQCMUWdHTviazPJBaGBIVMJazPxOPGBUaoFMja6wgP.amQCcuEbHjX8djQCEqraHjkQXzPm.3FBkB0EMzI.tgPi0VrxVzP5CVJBIFPXVzP7LVJB8bfEMzbHlhP88VQCgRzoHjXExUQCkFGpHzBSUzPsimJBsvTEMT9lqhPhsvTEMT4hshPFyUQCgwvqHjZvUzPke.KBIFCDVzPyxDKB0vlEMTEuwhPVUaQCUwarHjXB6bQCUwarHDIkWzPqwDKBoH9EMz0FvhPhU9BFMDDAuhPkVgQCsIXqHToUXzPwYtJBIVoUXzPlgmJBAFCFMTZbnhPcmeQCgRzoHjXAcdQCsjgoHzTPWzP5CVJBQSsEMj9fkhPhgEsEMj9fkhPKNaQCcNXoHTrxVzP5CVJBMVY...";
    
    icons.question = Content.createPath();
    icons.question.loadFromData(pathData);
    
    // Question circle - Reza
    pathData = "1194.t0F.xixP..kEBIlvHbxP++jEBAndkLDBKxgP.pWICA.LjHjX.pWICkO0qHjvHbxPA3fLBAf7nLD.NHiPh4y1pLz+MHiP.nFKCgO0qHD.pwxP..CIBIF.pwxPIrHGB4y1pLT.PYgP.HOJCA.TVHzXsAf7nLD.1igPhs6epLT.1igP.B7JCcQ9cHDf.uxP..CIBIFf.uxPoalJBs6epLz+m8hP.HOJCA.ZuHjXFQ1ICE.ZuHD.jXxPpalJBA.IlLD.vPhPhE.IlLjE42gPFQ1IC8e8XHD.xixP.XOFBMVaHmOJCc6saHjXqdKJCc6saHj48gxPmP+FBkESnLTJrwgPhwrFnLDKjygP0S+ICU+dcHzFaexP2JiGBIVPAexPcmtGBoGsmLT+c9gP5Q6IC0.TfHjX5Q6ICImofHTj7dxPvaOHBIMymLjz.EhPhoQ2mLT4JFhPiD+ICI+qgHj3HfxPx+ZHBIlFwfxPx+ZHBkHSnLj+EEhPmqEJCsdbfHjXunFJCw1oeHDr7gxP41vGBoqjnLzhk5gPhULpnLTW83gPprLJCAWBdHDx4ixPvkfGBI1igjxPvkfGBEgPoLj773gPHsUJCQ+ndHjX+QWJCgxBeHjGAlxPOo3GB4QfoLDaf.hPh4QfoLDbsAhP+yWJCgHsfHTqzkxP0XOHBIVcrkxPieSHBUjXoLTKyEhP+XUJCkHpgHjXinTJCcg2gHze1jxPy1hHBA1FoLTpVJhPhEG+nLDqNLhPpONJCAmciHDrQixPO27HBIlc+hxP6SBIBUNrnLDBJRhPlWJJC0X+jHjXcqIJC8MbkHDWUhxPikeIBwUknLDHWZhPhwUknLT.UbhPbyIJCE4bmHT2qhxPJM6IBIV25hxPCL+IBMVynLDDSfhPsMNJCAwDnHjXW2PJCAwDnHjEmjxPyF6IBkwKoLzatahPhg7LoLjjRZhP1bSJC4kTlHzh4jxPQ2hIBIV16jxPEkfIBAxOoLzejWhPRMTJCA7ukHjXRdTJCAvlkHDHNkxPMJWIBcrUoLjjFUhPh41WoLzkZThP.rVJCA64jHDb4kxPj1JIBI1gslxPJ78HBcZzoLjALMhPIWdJCgM8hHjXhmeJCwZmhHDSKnxP0ViHBkdFpLTr8FhPhcHJpLjqEEhP+9hJCkjtfHzuunxPWpAHBI1xunxPtB0GBwvHpLz2T5gPhkfJCYA5cHjXV+dJC82NcHTUKmxP5KKGBAFmoLzfNwgPh4UaoLjOpugP1bSJCM6saHTx4ixPyd6FBMVaPgMJCoHloHjXe2KJCsrloHjamhxPD.bJBwQknLTtHnhPhQhfnLj9SohPphGJC4GrpHjp3gxPI5wJBIlp3gxP0o4JBQlfnLDp5uhPHXIJCY2OrHjXqlJJCMDgrHzp.ixPlZJKBUu1nLjolxhPhEF8nLjolxhPCqPJCw+frHTJdjxPm4CKBIFgwjxPgh+JBQzNoLzJXthPDsSJCIfGqHjXDsSJCc+qpHD.xjxP5OkJBw2GoLjtHnhPhANCoLT28lhPxWOJCsHloHzzZixPKhYJBIlCZixPKhYJBoT1nLDdXlhPDgMJCsHloHzXkA..";
    
    icons.questionCircle = Content.createPath();
    icons.questionCircle.loadFromData(pathData);
    
    // Info - Reza
    pathData = "353.t0F..PfP...CBwF...fP...CBwF...fP...zAIF...fPBrxwA4O03GD...bP...7AA...GDa...3AA...GjXBrx0AA...GD...cPBrxwAA..PGD...cPhA..PGj+TicPBrx0AA..fGD...dP...3AwF...dP...CBwF..fcP...CBIl.q7bP...CBA..HGTfU9fP...xAA..THjX...xA8mZXHj.q7bP...GBA..XGD..vgPrA..DHD..vgPh8mZHHD..vgP...CB8mZXHD..vfP...EBIF..vfPAV4CB8mZHHD..vfP...ABA..LHzXsA..rGD...aPhoDC2GD...aP....BoDCmFD...fP...mAIF...fP1NOjAoDC2GD..fXP...6AA..HFjX1NO3AA..HFD..fcP1NOjAA..XGD..vYPhA..XGjRLbZP1NO3AA..vFD..vdP...rAMVY...";
    
    icons.info = Content.createPath();
    icons.info.loadFromData(pathData);

    // Info circle - Reza
	pathData = "573.t0VG93yPXsmJBw11L3yPXsmJBw11L3yP123HBI11L3yPsQqHBcK38LD3CHhPUoZOCA9.hHDaOeTOCA9.hHjXsEQOCA9.hHTRkyyPsQqHBkT47Lj8MNhPhkT47LzemQhPrEQOCw.FkHzyG0yPLfQIBw1yG0yPXsmJBwFiVzyPXsmJBIlJfyyPXsmJBc.s7LT4qrhPGPKOC4VArHjXGPKOCcu2rHjJfyyPD9XKBwnE8LDgO1hPr0gO9LDgO1hPh8Gc9LDgO1hPiBpOCcu2rHznf5yPtU.KBI1nf5yPkuxJBAHc9LDV6ohPc3iOCg0dpHzXsQaj8Lzx4AhPhsa08Lzx4AhPayfOC4TmeHz1L3yPvznGBI11L3yPRzWGBsa08LTkfxgPzFYOCUInbHjXr1TOCUInbHTiVzyPSzWGB0nE8LDLM5gPh0nE8LjSc9gPs1TOCsbdfHDsQ1yPKmGHBMVaBpZOCAfNWHjXCE7NCAfNWHjfxnyPHLWGBInL5LD.XThPhInL5LD97xhPCE7NCAf8xHjfp1yP.XuLBIFvS9yP.XuLBIfHAMD97xhPBHRPCA.FkHjXBHRPCgvbcHDvS9yP.nyEBInp8LD.5bgPi0lfp1yP.3cFBIFO37yP.3cFBIHd.MzEg6gPBhGPCA.FkHjXBhGPCktSqHTO37yP.HELBInp8LD.RAiPhcLG7LD.RAiPAvsNCktSqHT.bqyP.fQIBIV.bqyPWDtGBcLG7LD.dmgPBpZOCAf2YHzXkA..";
     
	icons.infoCircle = Content.createPath();
	icons.infoCircle.loadFromData(pathData);
    
    // Warning - Reza
    pathData = "242.t0F..fdP...EBIl.q7cP...EBA..XGTfUdgP...1AA..bHjX...1A8mZfHj.q7cP...IBA..nGD..PhPh4O0vGD..PhP...9A8mZfHD..feP...GBIF..fePAV4EB4O0vGD..PgP...5AA..THzXsULHnGjpweYPhc7ReGjpweYPECB1AwJGeFTwffcPpF+oAwVwffcPUi+.BIVwffcPZQFBBc7ReGT03ufPECB5AUM9KHjXCWO7Asc9KHTwffePTMFBBULH3GT03OfPrULH3GjpweZPhULH3GDqb7YPCWO7AoZ7WFTwffdPpF+kAMVY...";

	icons.warning = Content.createPath();
	icons.warning.loadFromData(pathData);
	
	// Warning circle - Reza
	pathData = "462.t0VzMMyPgNdJBI1bWLyPgNdJBM05xLDHTphPSstLCcYaqHjXSstLC4vQrHzbWLyPMdOKBEcSyLTi2yhPh8BgyLTi2yhPNA6LC4vQrHjSvNyPW11JBIlSvNyPfPoJB8BgyLTnimhPQ2zLCE53oHzXsYoSyLTmHvgPhgCFyLTmHvgPXvtLCwQtbHDFrKyPSJYGBwFFrKyPU4rIBIFFrKyP+e5IBgCFyLzRXghPV5zLCsDVnHjXyS3LC0GVnHzDwNyPMe5IBMQryLTUNahPrMQryLzjR1gPhMQryLDG4xgPyS3LC0IBbHjkNMyPch.GBMVaS3zLCAfnVHjXTSVLCAfnVHzjV+xPHrMGBMo0uLD..RhPhMo0uLD9jvhPUSVLCAfWxHzDNMyP.3kLBIVT2TyP.3kLBMgw1LD9jvhPSXrMCA.fjHjXSXrMCgv1bHTT2TyP.HpEBMgSyLD.hZgPi01DNMyP.XTFBIVyaSyP.XTFBMIG1LzEI4gPSxgMCA.fjHjXSxgMCktspHTyaSyP.n6KBMgSyLD.59hPhgEvwLD.59hPS.HLCktspHzD.ByP..HIBI1D.ByPWjjGBgEvwLD.FkgPS3zLCAfQYHzXkA..";
	
	icons.warningCircle = Content.createPath();
	icons.warningCircle.loadFromData(pathData);	
	
	// Warning triangle - Reza
	pathData = "1513.t01+4dnPmFckBIlbncnPmFckBMjIGJj0SXoPCYxgBMVYVJjXCYxgBAusVJjbncnPejukB8etGJzG4aoPhw3BHJzG4aoP61DhBAusVJztMgnPiUlkBI1tMgnPVOgkBw3BHJzoQWoP+m6gBcZzUJzXswxtGJjgeBoPh8YZGJjgeBoPvcxgBUa3PJDbmbnPBMSjBwFbmbnPqlJkBIFbmbnPKsOkB8YZGJzY8ToPrr6gBcVOUJjX4x.hBoWOUJD5NgnP3rOkBgtSHJzpoRoPrgtSHJjPyDoPhgtSHJTsgCoP4x.hBY3mPJDK6dnPF9IjBMVaop6gBobnKJDaop6gBobnKJDaxH6gBIfnKJDaAm5gBUpnKJDaZE5gBU6nKJDaDj4gB8RoKJDaCC4gBQwoKJDadh3gBIVpKJDaXB3gBcAqKJDa3h2gBIyqKJDaBD2gBAqrKJDa6k1gBEosKJDanH1gBAstKJDaMr0gBw1uKJDavP0gBEFwKJDaU1zgBwZxKJDa+bzgBszyKJDazDzgBgS0KJDa1sygBE21KJDaIXygBEe3KJDaxCygBUK5KJDaxvxgBg66KJDaafxgBAm8KJDaafxgBAm8KJDaskAfBUpKXJDaskAfBUpKXJDagUAfBUgMXJDa1FAfBYaOXJDat4.fBQXQXJDaKt.fBoWSXJDaOj.fBIYUXJDa5a.fBcbWXJDaPU.fBQgYXJDaPP.fBMmaXJDa7L.fBEtcXJDaTK.fBU0eXJDaXK.fB07gXJDaIM.fBEDjXJDakP.fB4JlXJDasU.fBwPnXJDafb.fBgUpXJDa7j.fBsXrXJDaAu.fBAZtXJDar5.fBMYvXJDa7GAfB0UxXJDatVAfBsOzXJDaAmAfBcF1XJDax3AfB042XJDa8KBfBco4XJDaffBfBIU6XJDaX1BfBk77XJDafMCfBge9XJDa1kCfBs8+XJDaU+CfB8VAYJDa5YDfB8pBYJDae0DfBg4CYJDaAREfBgBEYJDaauEfBoEFYJDaoMFfB4BGYJDakrFfB84GYJDaKLGfB0pHYJDaUrGfBQUIYJDa9LHfBQ4IYJDaBtHfBsVJYJDaaOIfBcsJYJDaCwIfBg8JYJDa0RJfB0FKYJDacxJfBcIKYJDacxJfBcIKYJDa0hriBcIKYJDa0hriBcIKYJDarDsiB8EKYJDaclsiBo6JYJDaDHtiBopJYJDaZotiB8RJYJDaZJuiBkzIYJDa+puiBsOIYJDaEKviBUjHYJDakpviBkxGYJDaaIwiBo5FYJDagmwiBk7EYJDazDxiBk3DYJDaNgxiBwtCYJDap7xiBYeBYJDaEWyiBoJAYJDaZvyiBwv+XJDakHziB4Q9XJDaieziBQt7XJDaN0ziBMF6XJDakI0iB8Y4XJDajb0iBwo2XJDaHt0iB800XJDaM90iBs9yXJDaxL1iBcDxXJDazY1iBYGvXJDaPk1iB4GtXJDaFu1iBQFrXJDaT21iB0BpXJDa381iB88mXJDavB2iB42kXJDa9E2iBEwiXJDaeG2iBsogXJDaTG2iBQheXJDacE2iBAacXJDa4A2iBQTaXJDap71iBcNYXJDaw01iB0IWXJDaNs1iBsFUXJDaCi1iBgESXJDaQW1iBgFQXJDa6I1iBAJOXJDaB60iBUPMXJDaCs0iBUpKXJDaCs0iBUpKXJDa2zDhBAm8KJDa2zDhBAm8KJDaMiDhBcy6KJDaGPDhBkC5KJDap6ChBoW3KJDa2kChB4u1KJDazNChBoL0KJDai1BhBMtyKJDaHcBhBoTxKJDanBBhBU.wKJDaFmAhBYwuKJDanJAhBAntKJDaQs.hBgjsKJDaGO.hB4lrKJDaMv+gBYuqKJDapP+gBM9pKJDahv9gBUSpKJDa5O9gB4toKJDa3t8gBEQoKJDagM8gB44nKJDa4q7gBYonKJDaHJ7gBoenKJDaop6gBobnKJDaop6gBobnKJzXskptGJjqc1nPrk4nMJz+YeoProazAJz+YeoPiUF...";
	
	icons.warningTriangle = Content.createPath();
	icons.warningTriangle.loadFromData(pathData);	
		
  	// Error circle - Reza
  	pathData = "506.t0F.V5wP.fhEBIVvrxwP.fhEBAnGaLDBiwgP.5wFCA.BjHjX.5wFCgOqqHjvrxwP.XdLBAfkdLD.lGiPh4yefLD.lGiP.1fHCgOqqHDfMHxP.f.IBIFfMHxPHLFGB4yefLD.nXgP.XoGCA.JVHzXsAfkdLD.NigPho6HfLD.NigP.RVHCcQzcHDfjExP.f.IBIFfjExPo6iJBo6HfLD..8hP.XoGCA.PuHjXEgPGCA.PuHDfGuwPo6iJBA3waLD.HPhPhA3waLzEQ2gPEgPGCAfyXHD.V5wP.3LFBMVav+.HCo6GdHjX8m9GC49gcHDar9wPteXGBomgeLjte3gPrAfkdLjzgGhProWocLjte3gPhc3ecLj6G1gPCHTGC49gcHDAbzwP59gGBIVD1ywPFdqGBEg8bLDxs9gPDvQGCIVQfHDaJxfGCo2AjHDaDvQGCAVxmHjXQXOGCwRXnHTD1ywPtcUJBQ.GcLjNumhPhcePcLjAGphP68WGCYvgpHjdk1wP57dJBwF.V5wPhzhIBwldF9wP57dJBIFar9wPFbnJB0e5eLjAGphPv+.HCoy6oHjXWWCHC41UoHz00.xPrDFJBQ9CfLjjIehPro1GeLjdGPhPrQ9CfLzjEAhPhQdMfLzws9gPjWCHCU3sdHD7O.xP49gGBMVY...";
  
	icons.errorCircle = Content.createPath();
	icons.errorCircle.loadFromData(pathData);

    // Search - Reza
    pathData = "317.t0F.fx.Q...zAIV1Vt.Q...zAA.vJPzHaqdP..rBDA..FHjX..rBDc8HMHDDnq.Qg.6DBErJKPjBWigPrsvIJPDZQjhPhoY.JPDdoshPZFfBD8SMuHzBmn.QO0XLBIFiLo.QeU9LBkUhJPzWkOiPZ6pBD8TiwHDaN96BDsfffHjXPJ.CDM1thHj1Nw.Q+++HBE.nLPz++OhPhgQpMPz++OhPA.nCDcVjVHT..5.Q++eABIV..5.Qgrs5AgQpMPj+++bPA.JCD4++OGzXsA.nLPDvJegPhEr.LPDvJegPTM3BDEuzOHDUCt.Q..fABIFUCt.QPfE9AEr.LPzepgdP..JCD8mZnGjXuzSCD8mZnGDq71.QPfE9AwJuMPD..XfPhwJuMPj7R+fPuzSCDArxWHD.fx.Q.q7EBMVY...";
    
    icons.search = Content.createPath();
    icons.search.loadFromData(pathData);

	// Hdd - Reza
	pathData = "556.t0lsyOhPw0CbAw146eYPw0CbAI15QYXPw0CbA8++uEzhrYXP+++aAYkCXFDa+++aAIt9iHjX+++aA4LyrHz5QYXPwJ+LBc99WFTrxOiProZbVHTrxOiPhEXEUHjhAGiPZl4DBQyLuHzHaIgP8mJKBw1zM0fPvzsHBIlPfafPc8fIB88S+GzYlehPOe+6Acl4mHjX1NutAcl4mHzy2+XPqFmDB878OFzpw+dPh878OFTCBraP1NutAQIFPFzy2+dPThAjAIF88IgPThAjAg99mHTCBraPnu+IBoZ7uGjXnu+IBEsH+Gz.qXhPXkqAB8QAiHDnZzfPrwJmtHDsHOgPhQ1tvHTPfSgPmumLBEY6UHjpwOiPAAtEBwlpwOiPV4.lAIlpwOiPKxlgA45wrHTb8.WP1N+HBEWOvEzXsEWuhHjmuUgPrUKREHjNzPfPrMEtTHzCsHhPhwy2VHDeTbhPmtQFBMw.oHzoajgPSLPJBIl030gPFtNKBASWiHzqGyhPTL3IBE.fnHjX2i5JBMENjHDxKuhPVieGBQw.nHDz2kgPhwf.nHT03kgP7mhIB0MoWHTb8JhPd9VEBMVad996AECBPGjXVNj2AECBPGjmu+bP3Ok2A446OGjsy+dPh446OGDvJCfPVNj2A446GHjmu+dPd99ABI1zMCfPd99AB878GHTvJCfPOe+ABc67uGjXOe+ABg+TdGzzMCfPwf.zA446uGTLH.cPiUF...";
	
	icons.hdd = Content.createPath();
	icons.hdd.loadFromData(pathData);

	// Folder - Reza
	pathData = "209.t0loaJhPrGExAIloaJhPrGExAkW5IHD6QgbPzLC4AwdTHGDaUM90AMamzFjXlY1zAQJbsFj+TibP...pAA...GD..fZPrQKxZFD..fZPhMGZPFD..fZP...hAgoavFD..fXPxKstAwF..fXPNdoFBIF..fXPzh7GBMGZPFD..PhPzhrlAA..jHDarxoHBA..jHjXGu7IBA..jHD..vhPzh7GBA..rHzgVpgPrA..rHT2jrcPhA..rHzf.CcPGu7IBwdTHGjoaJhPrGExAMVY...";
    
    icons.folder = Content.createPath();
    icons.folder.loadFromData(pathData);
    
    // Save
    pathData = "420.t0lT3xXPOJbY.IVEtlXPjBWS.oYlEFD...DPovUfAA...ADa...n.A...AjXBWOd.A...AD...DPZlYd.A...AD...JPrA...AD..fYPhA...ATyLCZPZlYd.A..nFD...JP...pAwF..fYP...pAIVyLCZP...pAA..nFTyLCZP...pAA..XFDa...pAw0i5CjX...pAoYloCD6QYZPtdT1.45QiFDov0LPrIEtLFDjBWFPi0F...TP...lAIFovURP...lAA..PDjqG0XP...DAA...FjX...DAQJbkEDovURP...TAA...ED...UPhw0iZED...UP...bAQJbkED...WP...fAIF...WPtdTiAw0iZED..fYP...PAA..XFzXsA..PED...QPrA..fCD...QPh0Ly7BD...QP...n.oYlADD...JP...3.IF...JPLyLu.0Ly7BD...JP...3.A..fBDa...TAA..fBjXZlYXAA..fBD...WPMyLu.A..vED...NPhA..vEjlYFPPZlYXAA..PDD...UP...DAMVY";
    
    icons.save = Content.createPath();
    icons.save.loadFromData(pathData);
    
    // Reset - Material Icons 16x16
    pathData = "373.t0lrnxCQNFJZCIl0FZCQYnATC4f0sPTzzGzPDeDIDIm2EMjXpjmEDg8aKMTkbr.QTfDdCUajIPjOAe4PhA.fGPjX+v6PltYEDgYAaOTImcBQXVv1CIVcmMCQXVv1C4ks8Pzjyy7PkbnPDAgs3NjXVs6PDA3pyNDCsGDQPAdqCkEI+PDTf25PhA.v8PDTf25Pp6FOD4XXuNDzTuCQzzcrCIlfTdCQnWBwCwmXsPjQ797Pv9iHDkOwJOjXWVdFDEREGOTnoLAQtZWtCgOYQPDeBi5PhY+NNPzwPt3PfTUFDQSWiMTImcBQzz0XCI14k1BQzz0XC0zMyPjX+11PzczMDYnI9MDapjYLDg8aJNjXnoyKDwUKONDKhCCQr1zkCY0NzPDqMc4PrQNuAQDqMc4PhooyCQDqMc4P..XQDAt5SND..VDQ0c7iCwF..VDQzhXZCIF..VDQJPBWCg8aAQjbdU0PVDwODoW1dMDayhJOD4XnnMzXkA";
    
    icons.reset = Content.createPath();
    icons.reset.loadFromData(pathData);
	
	// Open - Material Icons
    pathData = "268.t0lbb5CQjiiyCwlii4.QjiiyCwlii4.Q433VCwF..ZBQ433VCwF..ZBQ...PCwlii4.Q...PCIVxPp.Q...PCA.fGPzYlwzP..3ADkiiaMDa..3ADQNNNOjX..3AD4LyUOTxPp.Q...2C43XNPD..v8PrIGm9PD..v8PhclYBQD..v8P..XQD4LyUOD..VDQjiiyCwF..VDQ..fmCwlbb5CQ..fmCwlbb5CQjiiyCMVaNNVKDA...MDaNNVKDkiiaMDajDbNDkiiaMDaDU9ED0sewNDaRBLGDoWM6NDaxwoODM29tMDaxwoODQNNPNDa..XQDQNNPNDa..XQDA...MDaNNVKDA...MzXkA";

    icons.open = Content.createPath();
    icons.open.loadFromData(pathData);

	// Reverse - Material Icons 18x14
	pathData = "148.t01R9TAQxwwkCwF..d.QqpprCw1R9TAQjiiyCw1R9TAQ43XtCwlii0BQ43XtCwlii0BQbb7pCw1R9TAQbb7pCw1R9TAQxwwkCMVa..XQDYUUINDa0F7MDkiiaMDa0F7MDcbbBNDaxw4GDcbbBNDaxw4GDQNNPNDa0F7MDQNNPNDa0F7MD433jNDa..XQDYUUINzXkA";

	icons.reverse = Content.createPath();
	icons.reverse.loadFromData(pathData);
	
	// Repeat - Material Icons 18x20
	pathData = "184.t0VGGUAQxwwcCwF43dCQxwwcCwF43dCQjiCjCwF..VDQUUUZCwF43dCQiiiLCwF43dCQ333VCwlii4.Q333VCwlii4.QxwwkCwVGGUAQxwwkCwVGGUAQxwwcCMVaji6MDcbb.ODacbTEDcbb.ODacbTEDwwwqNDa..3ADYUUGODacbTED833hODacbTEDQNNNODaxwoODQNNNODaxwoOD433jNDaji6MD433jNDaji6MDcbb.OzXkA";
	
	icons.repeat = Content.createPath();
	icons.repeat.loadFromData(pathData);
	
	// Hive - Material Icons
	pathData = "387.t0FraCBQfscOCwF5srAQvL6XCwFraCBQ.VLgCwF9kvBQ.VLgCwFLRGCQvL6XCwF9kvBQfscOCMVa.XRCDA6IpMDaP.3ADg6+GNDa.XRCDA55ZNDaffGFDA55ZNDaXQhGDg6+GNDaffGFDA6IpMzXsgXhzPDrmn1PrA71tPDt+e3PrgXhzPDnqq4Prg51+PDnqq4PrA.fEQDt+e3Prg51+PDrmn1Pi0FpaCBQXPwhCwF1srAQ..fmCwFpaCBQnuNrCwF5kvBQnuNrCwFHRGCQ..fmCwF5kvBQXPwhCMVavWRCDgiNgNDa..3ADAhIzNDavWRCDgfDGODaXfGFDgfDGODaHQhGDAhIzNDaXfGFDgiNgNzXsAXhzPDN5D5PrA61tPDHlP6PrAXhzPDBRb7PrA51+PDBRb7Prg+eEQDHlP6PrA51+PDN5D5Pi0FlaCBQ.pysCwFzsrAQnYhxCwFlaCBQPIQ2CwF3kvBQPIQ2CwFFRGCQnYhxCwF3kvBQ.pysCMVY";
	
	icons.hive = Content.createPath();
	icons.hive.loadFromData(pathData);
	
	// Clock - Material Icons 19x20
	pathData = "277.t0FD3YBQA..PCIFYaUAQA..PCA.fGPDTMd2P..3ADA..dNjX..3ADgUN.ODYaUAQ...2CAAdlPD..v8PhwJm2PD..v8P..XQDgUN.OD..VDQ..fmCIF..VDQP03cCwJm2PT...zPPfmIDE...MzXsA.flPjlY97PhoDyXPjlY97PyLaCD01Y4NzLy1.Q..fmCI1Ly1.QThofCoDyXPjyLi0P..nID4LyXMjX1NCMD4LyXMTyL8CQThofC0LS+PD..34Ph0LS+PTamk6P1NCMDoYlOOD..ZBQZl4yCMVaMy.JDA..9MDalY1HDA..9MDalY1HDQyLjNDaMy5LDItt2NDa..fMDApFvNDaMy.JD0LieNzXkA";
	
	icons.clock = Content.createPath();
	icons.clock.loadFromData(pathData);

	// Update clock - Material Icons 24x24
	pathData = "321.t0F..VDQGgOjCwVN+7BQGgOjCwlc8fCQ5pNeCIFnG8BQ1fWVCsbwfPjGnf0P0+7EDIpl6MjXensCDE1kONzGZ6.QDbDqCU+yWPDEQ36PhsbwfPDIa+7PfdzKDQx1OOjc8fCQTDguCIVKzxCQ.UTsCk369PD61q5PI9tODo48cNDa..XQDo48cNjX..XQDwt8pNTlbJDQ3V8tCob07PjtAc7PhIITwPDvY38P9roGDAbFdOjAVLAQ5FzwCIVMYd.QCpGrCA.fGPDrzs3P3TvDDAuVoMjXvonGDEHy6Lz7DDCQAx7NCohh7PD7Zk1PrA.fEQDt1QzPrA.fEQzQ3C4Pi0lAZlBQv1vfCwlAZlBQrNumCwl0VTCQJrIqCwl24JCQmwHsCwFqsRBQD.9nCwFqsRBQv1vfCwlAZlBQv1vfCMVY";
	
	icons.updateClock = Content.createPath();
	icons.updateClock.loadFromData(pathData);

	// Hourglass bottom - Material Icons 12x20
	pathData = "157.t0F..VDQppp.DwlwxUDQUU0wCwVUUCCQ..fmCwlwxUDQsARZCwF..VDQppp1BwF..d.Qppp1BwF..d.QUUUZCwlppvAQ..fmCwF..d.QgqywCwF..d.Qppp.DwF..VDQppp.DMVaUUcDDA..eMDaUUcDDoppVLDappxNDoppVLDappxNDA..eMDa..nIDUU0XNDaUUcDDA..eMzXkA";
	
	icons.hourglassBottom = Content.createPath();
	icons.hourglassBottom.loadFromData(pathData);

	// Press - Material Icons 15x21
	pathData = "487.t0VDQjAQ8D0hCwVDQjAQNyLVCIVDQjAQnuePC0hrcPTd28xPlY1HDk2cuLjXfpQJDk2cuLzt61BQnuePCs6tsPjyLi0Prs6tsPTOQs3PhMAuxPDDeR3P..fMD03kxMD..XCQNyLVCIF..XCQLG5KCYRrsPDZl4vPlY1HDglYNLjXltQFDglYNLTyLCAQLG5KC0LyPPjyLi0Ph0LyPPziWJ2P5BAEDAwmDNTDQjAQ8D0hCMVaXzaPD43kwNDarjuKDoL5dNjXJUjKDYJUdNzzF1BQ..fmCgburPD..34PrkYloPD..34PrkYloPjyLi0PhkYloPjySrzPlRsIDE...MjYlMBQA..PCIlI3+AQA..PCMyLcPjySrzPyLSGD4LyXMDayLSGDowKEOjXqGkCD4q49NDZQ5.QnuuuCo8ANPD5666PhQ8uLPD5666PMd4BDQvC.OT6Cq.QFYavCwF..d.QHMExCwlKquAQjlR7CIF3HzAQHT17CculdPDyLS+PLyDHDwLyzODaF1EODwLyzOjXfb2ODwLyzOD1bGDQZCD7CwSTBQj92n9PrYsZEQDPm56PhsVcEQDGS36P..XQDoue8ND..VDQ9+OuCIF..VDQp+8sCgd6CQjHoM6PXzaPD43kwNzXkA";
	
	icons.press = Content.createPath();
	icons.press.loadFromData(pathData);

	// Trademark
	pathData = "2581.t0F.fs.Q..fmCwF.fs.Q..fmCwlqns.QcXKnCwVrBt.Q9o1nCwV9st.QnsgoCw1Zpu.QhbLpCwF32v.Q1u1pCwVIVx.QyffqCwF.Ez.QtnIrCwFJD1.QBAxrCwVSS3.QRiYsCw1Dx5.QII.tCwFEf8.QarktCwV3b.AQHGJuCwV.nCAQaSsuCw17.GAQrKOvCwlJmJAQfpuvCwVEZNAQppNwCw1EYRAQNGrwCwliiVAQd6GxCwly3ZAQ7BhxCwFJXeAQdY5xCwl3.jAQJ6PyCwlOxnAQZjkyCwldqsAQ5Q3yCwVyqxAQq.IzCwlZx2AQBtWzCwVf97AQnWjzCw1NOBBQZ6tzCw1viGBQtW2zCwlO6LBQMq8zCwFzTRBQ1zA0CwVmuWBQ.zC0CwlwJcBQTnC0CwlakhBQ1QA0CwVs9mBQ8v7zCwFvUsBQXF1zCwFsoxBQJSszCwls42BQvXhzCw16D8BQ1XUzCwFiJBCQhUFzCwFuIGCQPQ0yCwlrALCQtNhyCwVpwPCQ9PMyCwF2XUCQXa1xCw1i1YCQiwcxCw1BJdCQeWCxCwFnRhCQXQmwCwVoOlCQtiIwCw1c.pCQRSpvCwlejsCQDkIvCwVI6vCQRdmuCwV4CzCQZDDuCwVO91CQFcetCwlso4CQMt4sCwV3E7CQw8RsCwFWR9CQ.RqrCw1xN.DQNwBrCwF35ADQ8gYqCwlUVCDQvpupCwV7fDDQVREpCwlfZEDQdeZoCwF4BFDQAYunCwl+YFDQ3EDnCwF.fFDQ..fmCwF.fFDQ..fmCwF.fFDQ..fmCwlTWFDQjmzlCw1S8EDQDVIlCw1AREDQaRdkCwVkUDDQhiyjCwVHHCDQOPIjCwF2oADQReeiCwV.6+CQWW1hCwV168CQD+MhCwVsr6CQzblgCwF7M4CQ91+fCw16e1CQtSZfCwlHiyCQAxqeCwl.XvCQaYkdCwVD+rCQ4ngcCwl1XoCQPqfbCw16kkCQ5phaCwV6lgCQxwmZCwlcbcCQRIvYCwlMGYCQT56XCwV2mTCQOMKXCw1H+OCQ1IdWCwlwMKCQT2zVCwlhTFCQSbOVCw1MTACQu9sUCwllM7BQBjPUCwFgA2BQ1P2TCwVxvwBQPIhTCwVPbrBQlPQTCwlwDmBQnoDTCwFMqgBQTV7SCw1YPbBQAX3SCwlO0VBQXu3SCwlkZQBQTb8SCwlSALBQDdFTCw1PpFBQNySTCwFTVABQnYkTCwlSF7AQdN6TCwFE61AQPNUUCwFd0wAQ1TyUCw1Q1rAQZcUVCwFT9mAQdh6VCwlVNiAQ9ckWCwlImdAQKISXCw1bIZAQybDYCw180UAQ7P4YCwlXsQAQJcwZCwVWvMAQb3raCwlh+IAQTYqbCwFgaFAQw0rcCwF2DCAQUCwdCwFG7+.QE22eCwFwA8.Q1hffCw1RV5.QvQFgCwFH52.QKBsgCwVos0.Q8sThCwlMwy.QtN8hCwFHEx.Q.dliCw1pov.QLUPjCw1Ceu.Qms5jCwlekt.QdfkkCwFG8s.Q6lPlCwV.ls.QD56lCwF.fs.Q..fmCwF.fs.Q..fmCMVa..XQDA..dNDa..XQDA..dNDaUXWQDUTFgNDaZgUQD4HLjNDaiaRQDI9PmNDaOGNQDcTTpNDaJkHQDsrUsNDaM1AQD4mTvNDac64PDgmPyNDaJ1vPDgMI1NDaymlPDQ783NDa+QaPDAWt6NDai1NPDYAZ9NDadWAPDAf.AODa41xODMXgCODaJWiODQP7EODav5RODcuPHODaQjAOD8cdJODagVuNDAEkLODaZTbNDYOjNODa9fHNDYnaPODaX+yMDI8JRODa6xdMDw6wSODa+9HMDwSPUODaCmxLDI1kVODattaLDIUxWODanYDLDcj0XODagqrKDgYuYODaLnTKD0peZODadS7JD4PFaODaRwiJDYEiaODagEKJD4C1aODaJTxIDII+aODaHgYIDwS9aODabv.ID4iyaODa.FnHDU6daODazkOHDQc.aODavS2GDoNXZODatSeGD4UlYODaioGGD85pXODaBYvFDYGlWODa4kYFDIFXVODavSCFDoCAUODaNlsEDANgSODaufXEDYz3QODaqFDEDkGHPODaTavDDkYONODaxgcDDs8NLODaHcKDDgHGJODaNP5CDoO3GODaz8oCDAphEODahnZCDkuFCODazRLCDQ4j.ODa799BD4f88NDaEuxBDYAQ6NDaIkmBDQ1e3NDa8hcBDwap0NDaFpTBDEOwxNDa.7LBDwszuNDa5YFBD4U0rNDa1DABDQlyoNDaq87ADo8ulNDaDE5ADg6piNDaca3ADY+jfNDa..3ADA..dNDa..3ADA..dNDa..3ADA..dNDaqm3ADoq4ZNDald5ADA2yWNDacj8ADwAuTNDaw3ABDUqqQNDa2ZGBDASpNNDazINBDwWqKNDajDVBDIXuHNDa2IeBDEx1ENDaOXoBDQCBCNDaCtzBDgnQ.NDafIACDI7K6MDalnNCD4990MDaJIcCDYN8vMDa5nrCDMdGrMDaUE8CD4edmMDazaNDD4BCiMDakofDDkz0dMDasqyDDAf2ZMDaIeGED8sHWMDav.bEDgDpSMDaNMwEDQGbPMDaJAGFDQWeMMDaGYcFDoRzJMDacQzFDwTaHMDailKGDI1TFMDaqTiGDQLgDMDaAX6GDoo.CMDaurSHDscyAMDa7NrHDwz4.MDas5DIDE3S.MDaErcIDwsA.MDaGe1IDsXC.MDazOOJDg3X.MDaP5mJD4IBAMDacZ.KDMF+AMDagrXKDsiOCMDajrvKDgUyDMDatVHLDkKpFMDaPmeLDAyyHMDaYZ1LD00OKMDagrLMD858MMDaDZhMDkl8PMDahe2MDEZNTMDal4KND8yuWMDa8jeNDQPgaMDaddxNDUHheMDaHiDODEywiMDaBvUODAkOnMDaZBlODcv5rMDarW0ODgkxwMDaYsCPDUR11MDaOAQPDICE7MDaFQcPDMAu.NDa.anPDYLfCNDaLcxPD4lUFNDaAV6PDoyNINDaFDCQDAUKLNDaLlIQD4rJONDaN6NQDobLRNDaXBSQDMEPUNDa95UQDUGUXNDajjWQDgCaaNDa..XQDA..dNDa..XQDA..dNzXsA.zbPD7G32Pr8Q2nPD7G32PhAWeuPD7G32Pwv2LDYliFNTL7MCQbRgjCIVL7MCQlYtlCcn4vPjjcD5PmDaKDQLbiNDa..AMDA..8NDaovhKDA..8NDaWOHJDcSJkNDaP0eHDcSJkNDaP0eHDA..8NDa..MGDA..8NDa..MGDA+A9MzXsIE+gPzg1c3PrIE+gPDF7y4Pr4N+mPDF7y4Phg+0qPDF7y4PXUgKDEXYYNDVU3BQaGmjCIFVU3BQ240hC0gwqPzg1c3PjBBJDcncGNDaRweHDcncGNzXkA";
	
	icons.trademark = Content.createPath();
	icons.trademark.loadFromData(pathData);

	// Libre Wave logo
	pathData = "1199.t0Fv1w+P.jTACwFv1w+P.PZkCwFPyuAQ.PZkCwFPyuAQ.nPfCwF3Kp.Q.nPfCwF3Kp.Q.jTACwFv1w+P.jTACMVafmCHDAPRELDafmCHDA.oUNDa.nHKDA.oUNDa.nHKDAPRELDafmCHDAPRELzXsARhyPD.IUvPrARhyPD.jV4PrAbxHQD.jV4PhU7tRQD.jV4PfBRVDwCoLNDnfjEQ.3MeCIFnfjEQKq7YCcv2UQTp2b0P.eLTDAH8RMjXymQUDY29MMD.SeEQLJ.PCAvzWQDfx7xPhAvzWQzheVwP2tYTDAPRELDfleDQ.jTACwFHINCQ.jTACMVa.MiWDAPRELDa.MiWDA.oUNDa.OnZDA.oUNDa.OnZDAng9MDa.aPbDAng9MDa.gncDA.oUNDafAjfDA.oUNDafiAeDAfC0MjXWwDfDY02pMDbJFHQ8+MVCAmhARDf+.zPhAmhARj0XpwP9.KeDAPRELD.OFGQ.jTACwFPy3EQ.jTACMVavwHgDAPRELDavwHgDA.oUNDav3bkDA.oUNDav3bkDAjrBNDaPRqhDAjrBNDaPRqhDA3FqMDafCHkDA3FqMDafCHkDAHNEMDaPRqhDAHNEMDaPRqhDA.KqLDavIXkDA.KqLDavIXkDAPRELDavwHgDAPRELzXsAIFWRDfEVvPrAo8cRD.jV4PrACChRD.jV4PrAXtlRD.16xPrA4UqRD.jV4PrAMcuRD.jV4PrAuT1RDfEVvPrAROxRDfEVvPrAFhsRDv+O3PrAEwnRDfEVvPrAB2jRDfEVvPrA5GfRDv+O3PrA6VaRDfEVvPrAIFWRDfEVvPi0F3h1KQ.VXACwFnLRKQ.PZkCwF3ohKQ.PZkCwFn+oKQ.3AgCwFHeRLQ.3AgCwFD0YLQ.PZkCwFL3pLQ.PZkCwFL.GLQ.VXACwF3h1KQ.VXACMVaPfSxDAXgELDafrVzDA.oUNDafgX0DA.oUNDafHc2DAXgELDaPwa1DAXgELDavP4zDA7+CNDavrWyDAXgELDaPfSxDAXgELzXsAbcfSDfEVvPrAbcfSD.jV4PrA..vSD.jV4PrA..vSDvIe3PrASajSDvIe3PrASajSD.lW1PrAYetSD.lW1PrAYetSDfwnzPrASajSDfwnzPrASajSD.5DxPrAQouSD.5DxPrAQouSDfEVvPrAbcfSDfEVvPi0FDW9KQ.H1ICwFfyLLQ.BPaCwFbquKQ.BPaCwFDW9KQ.H1ICMVafr7ODAXNpLDafCzQDAXNpLjX+3ZRDAXNpLDH3rDQt71KCABNKQDf0eyPhABNKQTZ3BzP+3ZRDA3YFMD3.cDQ.dlQCwFHK+CQ.dlQCwFHK+CQ.liJCMVa.OnZDA.KqLDa.7XbDA.KqLjXKqScDA.KqLDPbcGQsjyLCADW2QD.qFzPhADW2QTGVB0PKqScDA3nXMD.OFGQ.NJVCwFvCpFQ.NJVCwFvCpFQ.vxJCMVafr7ODAHQnMDafCzQDAHQnMjXZOlRDs0.nMDXmwDQkYaaCA1YLQD.1Z2PhA1YLQDr0.3PZOlRDwbRCND3.cDQ.txfCwFHK+CQ.txfCwFHK+CQ.RDZCMVY...";
	
	icons.logo = Content.createPath();
	icons.logo.loadFromData(pathData);

    // Rhapsody Logo - Reza
    pathData = "129.t01muzuPn+3pBw1mRLqPlxZ8BwVk+TrPrx9.Cw1P51uPn50yBwFGsrvPa4+4BwV4iVuPa4+4BwFOGwsPVsJ.Cw1wfCvPVsJ.Cw1wfCvPjrYGCwlbrDvPkrYGCw1BC1vPLRTDCw1BC1vPWsJ.CwFsE1wPg3J.CwVIFNxPZxV8BMVY";
    
    icons.rhapsodyLogo = Content.createPath();
	icons.rhapsodyLogo.loadFromData(pathData);
	
	// Rhapsody logo with background
	pathData = "166.t01N1g0P4++NBwF9hQ0PDzDSBw1N1g0POnIWBwlWIx0PDzDSBMVaCdGVCUdoBIDaTKuVCkxjLIDaDtnVCUbKNIDaffWVCUMKNIDagfWVCYvnRIDaeOJVCw.8UIDaM6IVCUA8UIDaN6IVC4MKNIDadw0UC4MKNIDaLZCVCsQwJIDa7+TVCsQwJIDaXvGVCkXcGIDaCYoUC0MCOIDa.neUCE8lLIzXkA";
	
	icons.rhapsodyLogoWithBg = Content.createPath();
	icons.rhapsodyLogoWithBg.loadFromData(pathData);
}

